openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: https://nodejs-hw-mongodb-ihgx.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/path/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/path/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/path/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/path/auth/refresh.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/path/auth/send-reset-email.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/path/auth/reset-pwd.yaml

  /contacts:
    post:
      $ref: ../swagger/path/contacts/post.yaml
    get:
      $ref: ../swagger/path/contacts/get.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/path/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/path/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/path/contacts/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer